name: smart_receipts
description: Digital receipts project for thesis.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ## Core 
  provider: ^6.0.3 # Provider & Consumers
  intl: ^0.17.0 # DateTime formatting
  http: ^0.13.5 # HTTP requests 
  shared_preferences: ^2.0.15 # Shared Preferences
  qr_flutter: ^4.0.0 # QR Code generation

  ## UI
  flutter_slidable: ^2.0.0 # Mobile entry slidable 
  persistent_bottom_nav_bar: ^5.0.2 # Bottom nav bar
  currency_icons: ^0.3.0 # Currency icons for selection
  animated_splash_screen: ^1.3.0
  auto_size_text: ^3.0.0 # 
  shimmer: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/